<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Harga Properti Maksimal KamuRp 36.000.0_db86bc</name>
   <tag></tag>
   <elementGuidId>2209770e-f1d8-4f2a-8015-7eb5c37e44c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#harga_hasil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='harga_hasil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Harga Properti Maksimal KamuRp 36.000.000Langsung cari di area yang kamu inginka&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8135db4-08d9-47d9-a292-a30e824b0364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>harga_hasil</value>
      <webElementGuid>8ee0f98e-00ae-47be-a925-1f5a88454599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex justify-content-center flex-column</value>
      <webElementGuid>c73a5d05-30e6-4dc1-a22e-89c9760eac68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harga Properti Maksimal KamuRp 36.000.000Langsung cari di area yang kamu inginkanLokasi</value>
      <webElementGuid>d654d1f4-507f-41df-9b86-5fa8e4054535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harga_hasil&quot;)</value>
      <webElementGuid>a5b5d441-049f-46d0-a2fd-9eaf6fb2a71c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='harga_hasil']</value>
      <webElementGuid>fbf51e48-4b57-4163-b886-42276cd77e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='hitung_harga']/div/div/div/div[2]/div/div/div[3]/div</value>
      <webElementGuid>48e44775-c3be-432c-9d81-9c8e740979bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitung Ulang'])[1]/following::div[2]</value>
      <webElementGuid>08639ea6-913c-451f-bd3c-5bd313e7b1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangka Waktu'])[2]/following::div[3]</value>
      <webElementGuid>361050f2-6799-4573-9cbc-cc554a32cf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div</value>
      <webElementGuid>98382e46-4743-4862-b2e2-1cf8e71a7477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'harga_hasil' and (text() = 'Harga Properti Maksimal KamuRp 36.000.000Langsung cari di area yang kamu inginkanLokasi' or . = 'Harga Properti Maksimal KamuRp 36.000.000Langsung cari di area yang kamu inginkanLokasi')]</value>
      <webElementGuid>b7395cf7-fe30-4545-be37-33802852a5b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
