<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Ajukan KPR_menubar</name>
   <tag></tag>
   <elementGuidId>fa0b8511-2fdb-41eb-8673-d7827db1f902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menubar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Toggle navigation&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>19526d83-d06e-4e88-bb3b-c4cf68e4913d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-x-lg</value>
      <webElementGuid>c75219b7-6bfc-45be-a975-e088e93ab80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menubar</value>
      <webElementGuid>781c59a4-b996-46f3-aa9b-5774903317fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[@id=&quot;menu_mobile&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center w-100&quot;]/button[@id=&quot;iconMenu&quot;]/i[@id=&quot;menubar&quot;]</value>
      <webElementGuid>3ed2bcd9-a6db-423d-aee9-6ccb47ce9a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='menubar']</value>
      <webElementGuid>bb04883a-4ac7-471c-991b-8e4d648f8009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='iconMenu']/i</value>
      <webElementGuid>0cfe38cd-460c-4549-9a80-dc2bb420d5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>c4dbfdcc-6325-426f-a875-704a4e6c86fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'menubar']</value>
      <webElementGuid>811db5d9-d06b-42d8-8640-f1c0c4571a64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
